### PR TITLE
Ability to provide creds as login parameters

### PR DESCRIPTION
**Pull request by nmaupu**
Hi,

Here is a PR to optionally provide `username` and/or `password` as parameters instead of being actively asked using stdin.

### CODE REVIEW

**Comment by nmaupu** [comment]
ping @howardburgess

**Comment by nmaupu** [comment]
Nobody ?

**Comment by jsravn** [comment]
@nmaupu thanks for the contribution! I'll have a look tomorrow.

**Comment by nmaupu** [comment]
Ping @jsravn

**Review by jsravn — APPROVED** [review]

**Comment by jsravn** [comment]
@nmaupu Done! Sorry about the delay, and thanks again for the PR!

**Pull request merged**
