### PR TITLE
Add `config targets` command

### PR DESCRIPTION
**Pull request by totahuanocotl**
Allows a user to display the list of defined targets within the
client configuration. It can display the list of targets per group
and to target a specific group via flags.

It also makes every command work with targets in alphabetical
order, to get consistent ouputs across the operations.

Part of https://github.com/sky-uk/osprey/issues/9

### CODE REVIEW

**Comment by totahuanocotl** [comment]
After writing this PR the groups command seems a bit useless at the moment. Maybe it will make more sense if we start adding features so that we can alter the ospreyconfig through the command line.

I am also considering the idea of '""' (no group) to be a valid group, like in the targets. Since after this PR, without a named default group, `""` is the default group. And it can't exist if a named default group does. 
What do you think?

**Comment by lw346** [comment]
I agree that `config groups` is somewhat superfluous now, as it doesn't render different information to `config targets`, just in a different format.  I think we should remove the `config groups` command, and we can always add it back again if it becomes necessary at some point in future.  Given we haven't released a version of osprey with this command yet, that should be fine to do.

If `""` is a valid target, then it should probably be a valid group for consistency across the commands.

**Comment by totahuanocotl** [comment]
yeah, i thought so. Do you think it is worth adding a `---list-groups` flag  in the targets command so that we only list the groups without any targets? helpful if you only want a short view of all the groups.

**Comment by totahuanocotl** [comment]
I'll make those changes as part of this PR, get it merged, and then we can release

**Comment by lw346** [comment]
I think `--list-groups` would provide something that we don't otherwise have, so I think including it is a good idea.

**Pull request merged**
